---
- name: Install Apache
  apt: 
    name=apache2
    state=present

- name: Unlink default site
  file: 
    path={{ item }}
    state=absent
  with_items:
    - /etc/apache2/sites-available/default
    - /etc/apache2/sites-available/default-ssl
    - /etc/apache2/sites-enabled/000-default
  notify: 
    - restart apache

- name: Enable 'mod_rewrite'
  command: a2enmod rewrite
  notify:
    - restart apache

- name: Create fqdn configuration file (prevent apache error message 'Could not reliably determine the server's fully qualified domain name ...')
  copy:
    dest=/etc/apache2/conf.d/fqdn
    content="ServerName localhost"
  notify:
    - restart apache

- name: Make sure Apache is up and running
  service:
    name=apache2
    state=started